### ISSUE TITLE
`/click synthesize` throws exception on CN 6.15

### ISSUE THREAD

**Issue by StarHeartHunt** [daemitus/SomethingNeedDoing#104]
Log:
```
2022-10-18 20:38:21.012 +08:00 [DBG] [SomethingNeedDoing] Executing: /click synthesize
2022-10-18 20:38:21.014 +08:00 [ERR] [SomethingNeedDoing] Unexpected click error
ClickLib.Exceptions.InvalidClickException: Addon is not available
   at ClickLib.Bases.ClickBase`1.GetAddonByName(String name, Int32 index)
   at ClickLib.Bases.ClickBase`1..ctor(String name, IntPtr addon)
   at lambda_method528(Closure , IntPtr )
   at ClickLib.Click.SendClick(String name, IntPtr addon)
   at SomethingNeedDoing.Grammar.Commands.ClickCommand.Execute(ActiveMacro macro, CancellationToken token)
```

**Comment by StarHeartHunt** [comment]
It seems to be caused by the hook is injected too early (when the game just starts). Starting Dalamud after login solves this.
