### ISSUE TITLE
command /click synthesize doesn't work after the last update

### ISSUE THREAD

**Issue by tmschorr** [daemitus/SomethingNeedDoing#116]
The command /click synthesize doesn't work after the last update.

[SND] Failure while running /click synthesize  (step 1): Unexpected click error

**Comment by Zereah** [comment]
Second this. Nearly every command is broken, trying to skip to the next step just causes the Peon to die unexpectedly.

**Comment by guppyfaced** [comment]
same - see attached error segment

running on the stg branch
```
ERR [SomethingNeedDoing] Unexpected click error
System.InvalidOperationException: Function pointer for AtkStage.GetSingleton is null. The resolver was either uninitialized or failed to resolve address with signature E8 ?? ?? ?? ?? 0F BF D5 ?? ?? ?? ?? ?? ?? ?? ??.
   at FFXIVClientStructs.FFXIV.Component.GUI.AtkStage.GetSingleton() in :line 23
   at ClickLib.Bases.ClickBase`1.GetAddonByName(String name, Int32 index)
   at lambda_method2222(Closure, IntPtr)
   at ClickLib.Click.SendClick(String name, IntPtr addon)
   at SomethingNeedDoing.Grammar.Commands.ClickCommand.Execute(ActiveMacro macro, CancellationToken token)
```

**Comment by Maekir7** [comment]
this just got fixed very fast, upgrade it guys

**Comment by daemitus** [comment]
:)
