### ISSUE TITLE
Unable to use Lua

### ISSUE THREAD

**Issue by ONBBss** [daemitus/SomethingNeedDoing#132]
sorry to bother you, No matter how I set up Lua, it says "[SND]Peon has died unexpectedly."
Even though I used this halfway through crafting：
```
if (IsCrafting()) then
yield('/echo Yes')
else
yield('/echo NO')
end
```
Is there anything wrong with this?

**Comment by daemitus** [comment]
gonna need the  logs from /xldata

**Comment by ONBBss** [comment]
I am a Chinese player, the Chinese meaning at the end of the second line is "Trying to load program with an incorrect format"
My game and dalamud are both in the M:\ directory, is this the reason?

```
2023-06-05 18:42:45.973 +08:00 [ERR] [SomethingNeedDoing] Unhandled exception occurred
System.BadImageFormatException: Could not load file or assembly 'KeraLua, Version=1.3.1.0, Culture=neutral, PublicKeyToken=6a194c04b9c89217'. 试图加载格式不正确的程序。
File name: 'KeraLua, Version=1.3.1.0, Culture=neutral, PublicKeyToken=6a194c04b9c89217' ---> System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyBinder, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadAssemblyFromFilePath(String path)
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at SomethingNeedDoing.Misc.ActiveMacro.InitLuaScript()
   at SomethingNeedDoing.Misc.ActiveMacro.GetCurrentStep() in D:\a\SomethingNeedDoing\SomethingNeedDoing\SomethingNeedDoing\Misc\CommandInterface.cs:line 120
   at SomethingNeedDoing.Managers.MacroManager.ProcessMacro(ActiveMacro macro, CancellationToken token, Int32 attempt) in D:\a\SomethingNeedDoing\SomethingNeedDoing\SomethingNeedDoing\Grammar\Modifiers\EchoModifier.cs:line 10
   at SomethingNeedDoing.Managers.MacroManager.EventLoop() in D:\a\SomethingNeedDoing\SomethingNeedDoing\SomethingNeedDoing\Grammar\Modifiers\EchoModifier.cs:line 20
```

**Comment by ONBBss** [comment]
I am a Chinese player, the Chinese meaning at the end of the second line is "Trying to load program with an incorrect format"
My game and dalamud are both in the M:\ directory, is this the reason?
```
2023-06-05 18:42:45.973 +08:00 [ERR] [SomethingNeedDoing] Unhandled exception occurred
System.BadImageFormatException: Could not load file or assembly 'KeraLua, Version=1.3.1.0, Culture=neutral, PublicKeyToken=6a194c04b9c89217'. 试图加载格式不正确的程序。
File name: 'KeraLua, Version=1.3.1.0, Culture=neutral, PublicKeyToken=6a194c04b9c89217' ---> System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(IntPtr ptrNativeAssemblyBinder, IntPtr ptrAssemblyArray, Int32 iAssemblyArrayLen, IntPtr ptrSymbols, Int32 iSymbolArrayLen, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadAssemblyFromFilePath(String path)
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at SomethingNeedDoing.Misc.ActiveMacro.InitLuaScript()
   at SomethingNeedDoing.Misc.ActiveMacro.GetCurrentStep() in D:\a\SomethingNeedDoing\SomethingNeedDoing\SomethingNeedDoing\Misc\CommandInterface.cs:line 120
   at SomethingNeedDoing.Managers.MacroManager.ProcessMacro(ActiveMacro macro, CancellationToken token, Int32 attempt) in D:\a\SomethingNeedDoing\SomethingNeedDoing\SomethingNeedDoing\Grammar\Modifiers\EchoModifier.cs:line 10
   at SomethingNeedDoing.Managers.MacroManager.EventLoop() in D:\a\SomethingNeedDoing\SomethingNeedDoing\SomethingNeedDoing\Grammar\Modifiers\EchoModifier.cs:line 20
```

**Comment by q254387940** [comment]
> 需要来自 /xldata 的日志
> […](#)

how to use it
