### ISSUE TITLE
font problem

### ISSUE THREAD

**Issue by tssailzz8** [daemitus/SomethingNeedDoing#8]
in chinese game,the Chinese font will be display as ??.
the project add the click features recently,but i do not konw how to use it.Can you tell me how to use?

**Comment by tssailzz8** [comment]
[SomethingNeedDoing] Peon has died unexpectedly. this is my command is error？

**Comment by daemitus** [comment]
Find the error in your dalamud.log, and paste it here

**Comment by tssailzz8** [comment]
2021-10-14 11:17:30.382 +08:00 [ERR] [SomethingNeedDoing] Unhandled exception occurred
ClickLib.ClickNotFoundError: Invalid click
   at ClickLib.Click.SendClick(String name, IntPtr addon) in D:\a\SomethingNeedDoing\SomethingNeedDoing\lib\ClickLib\ClickLib\Click.cs:line 53
   at SomethingNeedDoing.MacroManager.ProcessClickCommand(String step)
   at SomethingNeedDoing.MacroManager.ProcessMacro(ActiveMacro macro, CancellationToken token)
   at SomethingNeedDoing.MacroManager.EventLoop(CancellationToken token)

**Comment by daemitus** [comment]
It doesn't work like that, I have to specify each individual button. Like
in the one I linked, you can use /click synthesize in the recipe window.
But not the recipe name itself.

**Comment by tssailzz8** [comment]
oh,thanks.i konw how to use it.
